ep3-rails/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :produtos do
    resources :pedidos, only: [:new, :create]
end

  get 'pages/sobre'
  get 'pages/contato'
  get 'vendedor' => "produtos#vendedor"
  get 'vendas' => "pedidos#vendas"
  get 'compras' => "pedidos#compras"

  root 'produtos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ep3-rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ep3-rails/app/models/pedido.rb
class Pedido < ApplicationRecord
    validates :endereco, :cidade, :estado, presence: true

    belongs_to :produto, :optional => true
    #Relacionamento entre dois modelos
    belongs_to :comprador, class_name: "User", :optional => true
    belongs_to :vendedor, class_name: "User" , :optional => true

end

ep3-rails/app/models/produto.rb
class Produto < ApplicationRecord
  has_attached_file :image, styles: { medium: "200x>", thumb: "100x100>" }, default_url: "placeholder.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
  validates :nome, :descrição, :preço, presence: true
  validates :preço, numericality: { greater_than: 0}
  validates_attachment_presence :image
  
  # Cada produto pertence a um usuario
  belongs_to :user
  has_many :pedidos
  
end

ep3-rails/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  cattr_accessor :current_user
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true

  has_many :produtos, dependent: :destroy
  has_many :vendas, class_name: "Pedido", foreign_key: "vendedor_id"
  has_many :compras, class_name: "Pedido", foreign_key: "comprador_id" 
end

ep3-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	
	before_action :configure_permitted_parameters, if: :devise_controller?

  def set_current_user

  		User.current_user = current_user
  end
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:admin])
  end

end

ep3-rails/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def sobre
  end

  def contato
  end
end

ep3-rails/app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /pedidos
  # GET /pedidos.json
  
  def vendas
    @pedidos = Pedido.all.where(vendedor: current_user).order("created_at DESC")
  end

  def compras
    @pedidos = Pedido.all.where(comprador: current_user).order("created_at DESC")
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
    @produto = Produto.find(params[:produto_id])
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)
    @produto = Produto.find(params[:produto_id])
    @vendedor = @produto.user

    #PREENCHE AS COLUNAS DO BANCO COM ID DO USER CONECTADO
    @pedido.produto_id = @produto.id
    @pedido.comprador_id = current_user.id
    @pedido.vendedor_id = @vendedor.id

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to root_url, notice: 'Pedido foi criado com sucesso' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_params
      params.require(:pedido).permit(:endereco, :cidade, :estado)
    end
end

ep3-rails/app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

    before_action :set_produto, only: [:show, :edit, :update, :destroy]
    #Permissões (devise)
    before_action :authenticate_user!, only: [:vendedor, :new, :create, :edit, :update, :destroy]
    before_action :check_user, only: [:edit, :update, :destroy]
  

  
  def vendedor
    @produtos = Produto.where(user: current_user).order("created_at DESC")
  end

  # GET /produtos
  # GET /produtos.json
  def index
    
    @produtos = Produto.all.order("created_at DESC")
    
    @produtos = Produto.where(["nome LIKE ?","%#{params[:search]}%"])
  
  end
  
  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)
    #Produto --> user_id
    @produto.user_id = current_user.id

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto cadastrado com sucesso' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :descrição, :preço, :image)
    end

    def check_user 
      if current_user.admin == false && current_user != @produto.user
        redirect_to root_url, alert: "Este produto pertence a alguém"
      end
    end
end

ep3-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

ep3-rails/app/helpers/devise_helper.rb
module DeviseHelper
    def devise_error_messages!
    return '' if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)
    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <h4>#{sentence}</h4>
    #{messages}
    </div>
    HTML
            html.html_safe
        end
    end
    
    

ep3-rails/app/helpers/pages_helper.rb
module PagesHelper
end

ep3-rails/app/helpers/pedidos_helper.rb
module PedidosHelper
end

ep3-rails/app/helpers/produtos_helper.rb
module ProdutosHelper
end

ep3-rails/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
  
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">MerkatOn</a>   
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><%= link_to "Contato", pages_contato_path %></li>
      <li><%= link_to "Sobre", pages_sobre_path %></li>
      </ul>

      <%= form_tag produtos_path, :method => 'get', class: "navbar-form navbar-right" do %>
          <%= text_field_tag :search, params[:search], placeholder: "Buscar Produtos",class: "form-control" %>
          <%= submit_tag "Buscar", class: "btn btn-danger" %>
          <% end %>


      <ul class="nav navbar-nav navbar-right">
      
       <% if user_signed_in? %>
           <% if current_user.admin == false %>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Minhas Vendas <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Meus produtos", vendedor_path %></li>
                    <li><%= link_to "Histórico de Vendas", vendas_path %></li>
                  </ul>
                </li>
          <% end %>

          <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <% if current_user.admin == false %>
            <li><%= link_to "Histórico de Compras", compras_path %></li>
        <% end %>
      <li><%= link_to "Editar perfil", edit_user_registration_path %></li>
      <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
      </ul>
    </li>
        <% else %>
      <li><%= link_to "Entrar", new_user_session_path %></li>
      <li><%= link_to "Cadastre-se", new_user_registration_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

ep3-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MerkatOn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('favicon.ico') %>

  </head>
  <body>

  <%= render 'layouts/header' %>
  
    <div class="container-fluid">

    <% flash.each do |name, msg| %>

<% if msg.is_a?(String) %>

<div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> alert-dismissable">

<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>

<%= content_tag :div, msg, :id => "flash_#{name}" %>

</div>

<% end %>

<% end %>


    <%= yield %>  
    </div>

  </body>
</html>

ep3-rails/app/views/pages/contato.html.erb
<h1>Contato</h1>
<p>Lucas Leite Macedo Maduro - 17/0016811</p>
<p>lucasleitemm@hotmail.com</p>
<br>
<p>Guilherme Mendes Pereira - 17/0129411</p>
<p>guimendesp12@gmail.com </p>

ep3-rails/app/views/pages/sobre.html.erb
<h1>Sobre</h1>
<br>
<p>Plataforma de venda e compra de produtos</p>
<p>A aplicação web consiste em um mercado online de compra e venda, onde usuários podem divulgar seus produtos e serviços diversos após efetuarem o cadastro/login no site.</p>

ep3-rails/app/views/pedidos/_form.html.erb
<%= form_with(model: [@produto, @pedido], local: true) do |form| %>
  <% if pedido.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dimiss="alert" aria-hidden="true">&times;</button>
      <h4>Preencha os dados necessários</h4>

      <ul>
      <% pedido.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :endereco %>
    <%= form.text_field :endereco, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :cidade %>
    <%= form.text_field :cidade, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :estado %>
    <%= form.text_field :estado, class: "form-control" %>
  </div>

  <div class="form-group">
    
   
    <%= form.submit "Completar Compra", class: "btn btn-success"%>
  </div>
<% end %>

ep3-rails/app/views/pedidos/compras.html.erb
<div class="center">
<h2>Histórico de Compras</h2>
<br>
</div>

<table class="table table-striped table-bordered">
    <tr>
        <th class="center">Imagem</th>
        <th class="center">Item</th>
        <th class="center">Preço</th>
        <th class="center">Vendedor</th>
        <th class="center">Data da Compra</th>
    </tr>

    <% @pedidos.each do |pedido|%>
        <tr>
            <td class="center"><%= image_tag pedido.produto.image.url(:thumb) %></td>
            <td class="center"><%= pedido.produto.nome %></td>
            <td class="center"><%= number_to_currency(pedido.produto.preço, unit: "R$ ", separator: ",", delimiter: "") %></td>
            <td class="center"><%= pedido.vendedor.name %><br><%= pedido.vendedor.email %></td>
            
            <td class="center"><%= pedido.created_at.strftime("%0d/%m/%Y") %></td>

        </tr>
            <%end%>
        </table>

<%= link_to 'Voltar', produtos_path, class: "btn btn-link"%>

ep3-rails/app/views/pedidos/new.html.erb
<h1>Novo Pedido</h1>

<%= render 'form', pedido: @pedido %>

<%= link_to 'Back', produto_path(@produto) %>

ep3-rails/app/views/pedidos/vendas.html.erb
<div class="center">
<h2>Histórico de Vendas</h2>
<br>
</div>

<table class="table table-striped table-bordered">
    <tr>
        <th class="center">Imagem</th>
        <th class="center">Item</th>
        <th class="center">Preço</th>
        <th class="center">Cliente</th>
        <th class="center">Data da Venda</th>
    </tr>

    <% @pedidos.each do |pedido|%>
        <tr>
            <td class="center"><%= image_tag pedido.produto.image.url(:thumb) %></td>
            <td class="center"><%= pedido.produto.nome %></td>
            <td class="center"><%= number_to_currency(pedido.produto.preço, unit: "R$ ", separator: ",", delimiter: "") %></td>
            <td class="center"><%= pedido.comprador.name %><br><%= pedido.comprador.email %></td>

            <td class="center"><%= pedido.created_at.strftime("%0d/%m/%Y") %></td>

        </tr>
        <%end%>
</table>

<%= link_to 'Voltar', produtos_path, class: "btn btn-link"%>

ep3-rails/app/views/produtos/_form.html.erb
<%= form_with(model: produto, html: { multipart: true }, local: true) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dimiss="alert" aria-hidden="true">&times;</button>
      <h4>Preencha os dados necessários corretamente </h2>

    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nome %>
    <%= form.text_field :nome, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :descrição %>
    <%= form.text_area :descrição, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :preço %>
    <%= form.text_field :preço, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :imagem %>
    <%= form.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

ep3-rails/app/views/produtos/edit.html.erb
<h1>Editando Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Mostrar', @produto, class: "btn btn-link" %> |
<%= link_to 'Voltar', produtos_path, class: "btn btn-link"%>

ep3-rails/app/views/produtos/index.html.erb
<div class ="center">
<div class="row">
  <% @produtos.each do |produto| %>
    <div class="col-md-3">
      <div class="thumbnail">
      <%= link_to image_tag(produto.image.url), produto %>
      <div class="caption">
        <h3><%= produto.nome %></h3>
        <h4><b><%= number_to_currency(produto.preço, unit: "R$ ", separator: ",", delimiter: "")%></b></h4>
        <p><%= "Anunciado por #{produto.user.name}" %></p>   
      </div>
    </div> 
    </div>

  <% end %>
</div>
</div>

<% if user_signed_in? %>
<%= link_to 'Novo Produto', new_produto_path, class: "btn btn-success" %>

<% end %>

<br>
<br>

ep3-rails/app/views/produtos/new.html.erb
<h1>Novo Produto</h1>
<%= render 'form', produto: @produto %>
<%= link_to 'Voltar', produtos_path, class: "btn btn-link" %>

ep3-rails/app/views/produtos/show.html.erb
<div class = "row">
  <div class="col-md-6">
  <div class="thumbnail">
    <%= image_tag @produto.image.url %>
    </div>
  </div>
  <div class="col-md-6">
    <h3><%= @produto.nome %></h3>
    <p><%= number_to_currency(@produto.preço, unit: "R$", separator: ",", delimiter: "")%></p>
    <p><%= @produto.descrição %></p>
    <br>
    <div>
    <% # Usuário não pode comprar seu próprio produto %>
    <% if current_user != @produto.user %>
    <%= link_to "Comprar agora", new_produto_pedido_path(@produto),class: "btn btn-primary"%>
    <% end %>
    </div>
  </div>
</div>

<% if current_user == @produto.user %>
<%= link_to 'Editar', edit_produto_path(@produto), class: "btn btn-link" %> |
<% end %>
<%= link_to 'Voltar', produtos_path, class: "btn btn-link" %> 


<% if current_user != nil %>
  <% if current_user.admin == true %>
 | <%= link_to 'Editar', edit_produto_path(@produto), class: "btn btn-link" %> |
  <%= link_to 'Excluir', @produto, method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse produto?' }, class: "btn btn-link" %>

  <% end %>

<% end %>

ep3-rails/app/views/produtos/vendedor.html.erb
<table class="table table-striped table-bordered">
    <tr>
        <th class="center">Imagem</th>
        <th class="center">Nome</th>
        <th class="center">Descrição</th>
        <th class="center">Preço</th>
        <th class="center">Produto</th>
    </tr>

    <% @produtos.each do |produto|%>
        <tr>
            <td class="center"><%= image_tag produto.image.url(:thumb) %></td>
            <td class="center"><%= produto.nome %></td>
            <td class="center"><%= produto.descrição %></td>
            <td class="center"><%= number_to_currency(produto.preço, unit: "R$ ", separator: ",", delimiter: "") %></td>
            <td class="center">
            <div class="btn-group">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Opções <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li><%= link_to "Visualizar", produto, class: "btn btn-link" %></li>
                    <li><%= link_to "Editar", edit_produto_path(produto), class: "btn btn-link"%></li>
                    <li><%= link_to 'Excluir', produto, method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse produto?' }, class: "btn btn-link" %></li>
                </ul>
                </div>
            </td>
            </tr>
        <%end%>
        </table>

<% if user_signed_in? %>
<%= link_to 'Novo Produto', new_produto_path, class: "btn btn-success" %>
<% end %>